Structure: Ducks # two options: Rails or Ducks

# Thunks: included 

# Logging: false will not generate with logging middleware

Models: # these are the separate slices of state that will be defined

  - Dux:

    Slice:
      - Name: string
      - Quacking: Boolean
      - Ducklings: Object
      - Fly2Gether: Boolean

    Actions: # additional actions
      - countDux
      - migrateAll
      
    Thunks: 
      - Fly2Gether:
        - '/api/dux/' 
        - migrateAll 
      - bulkMigration:
        - '/api/dux/' 
        - migrateAll 
    # - Thunk Name
    #     - Endpoint
    #     - Action to dispatch at conclusion of thunk  