Structure: Rails # Two options: Rails || Ducks

# Thunks: included # thunks will be included in the same file as the actions
# Logging: false  # configures logging middleware

Models:
  - dux:

    Slice:
      - name: string
      - Quacking: Boolean
      - Ducklings: Object
      - Fly2Gether: Boolean

    CRUD: true
    Actions:
      - countDux
      - migrateDux
      - quackOne
    Thunks:
      - getAll: "/api/dux"
      - getOne: "/api/Dux/:dux"
  # - Terminator:
  #   Slice:
  #     - WillBeBack: Boolean
  #     - OneLiners: Array
  #     - Sequels: Number
  #   Actions:
  #     - killJohnConnor
  #     - backInTime
  #   Thunks:
  #     - getAll: "api/terminator"
  #     - getOne: "api/terminator/:terminator"
